### ISSUE TITLE
A silent mode would be cool 

### ISSUE THREAD

**Issue by bgreg** [rking/ag.vim#108]
When Ag goes through large files it will render the text on the screen until the search is over.  Is there already a configuration option to disable this behavior?

**Comment by losingkeys** [comment]
I don't believe so (sorry for the radio silence). Good idea, let's add it :).

**Comment by bgreg** [comment]
Ok, I'll take a look when I get some downtime.

**Comment by losingkeys** [comment]
Quick correction after reading this again: there's probably a way to avoid showing the search text, but I don't think there's a way to search in the background without using something like vim-dispatch or neovim.

**Comment by bgreg** [comment]
That's a good point. I'll close this.

**Comment by coderofsalvation** [comment]
tried many things (keymapping using <silent> or silent!) however nothing helped.
This is the closest I got (unbuffering using a bit of bashfu):

     set grepprg=echo\ -e\ \"\$(ag\ --nogroup\ --nocolor\ --ignore-case\ --column\ $*)\""

Looks more peaceful :)
