### ISSUE TITLE
Ag opens the first search result by default

### ISSUE THREAD

**Issue by danihodovic** [rking/ag.vim#121]
Hi,

As soon as I enter the command `:Ag -Q <string>` and hit enter ag.vim seems to open the first result in a tab by default. How can I disable this behaviour?

**Comment by dani-h** [comment]
If anyone else wants the behavior of not opening the first search result you can use `:Ag!` instead of `:Ag`

**Comment by jamesmartin** [comment]
@danihodovic thanks, that's really helpful. :zap:

**Comment by danihodovic** [comment]
@jamesmartin If you're actively using ag in vim you might also want to check out https://github.com/junegunn/fzf.vim and the :Ag that's provided there.

**Comment by losingkeys** [comment]
Closed in favor of #119
