### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by deadlylaid** [rking/ag.vim#134]
I use window10 + VM(ubuntu)/ pyenv+virtualenv 

I think that 'ag.vim' is very awesome plugin!

so I decided to install it in my vimrc!

$Plugin 'rking/ag.vim'

:source %
:PluginInstall

but.... Unfortunatly... it doesn't work....

please help me...

부탁드립니다.

![1](https://cloud.githubusercontent.com/assets/16588261/13988875/46494c9a-f151-11e5-9130-b7410ff0afa0.png)
![2](https://cloud.githubusercontent.com/assets/16588261/13988876/49460bae-f151-11e5-9d18-20dd5212637a.png)

**Comment by losingkeys** [comment]
Looks like you may need to install the `silversearcher-ag` package in ubuntu.
