### ISSUE TITLE
How to search within specific subdirectories?

### ISSUE THREAD

**Issue by airblade** [rking/ag.vim#137]
I have this bash function to search all the stylesheets in a Rails app:

```sh
ags() {
  ag "$@" app/assets/stylesheets/ lib/assets/stylesheets/ vendor/assets/stylesheets/
}
```

I'd like to replicate that in Vim, i.e. be able to type `:Ags TEXT` and have the plugin search the three stylesheets directories.

What's the best way to achieve this?  With a new command, or a map, or something else?

**Comment by losingkeys** [comment]
You can use `:Ag search-for app/assets/stylesheets/ lib/assets/stylesheets/ vendor/assets/stylesheets/` or (if you want spaces in your search query) `:Ag "search for" app/assets/stylesheets/ lib/assets/stylesheets/ vendor/assets/stylesheets/`.

This is a pretty thin wrapper around ag, so you even do things like pass in command line options (e.g. `:Ag "search for" --literal dir/`).

**Comment by airblade** [comment]
Thanks – however I was after a way to pass all the directories automatically.  For example:

`:CustomAgCommand search for`

– which would then do the equivalent of:

`:Ag "search for" app/assets/stylesheets lib/assets/stylesheets vendor/assets/stylesheets`

**Comment by airblade** [comment]
Never mind, this does what I want:

```viml
command -nargs=1 Ags Ag <args> app/assets/stylesheets lib/assets/stylesheets vendor/assets/stylesheets
command -nargs=1 Agj Ag <args> app/assets/javascripts lib/assets/javascripts vendor/assets/javascripts
```
