### ISSUE TITLE
Ignore filetypes

### ISSUE THREAD

**Issue by garand** [rking/ag.vim#138]
If this is already possible and I missed something, please let me know.

I would like to search the project for a string but exclude a certain filetype. For instance, this morning I was searching a codebase for a string and wanted to find where it was in the markup (PHP file in this case). When I searched though, I get tons of results for where it was in many different CSS files and that clogged up my results with stuff I didn't care about. If I could have set something to ignore any *.css/*.scss file that would have been amazing. Or even *just* search *.php files.

What do you think?

**Comment by losingkeys** [comment]
You can pass options to ag through ag.vim. Ag supports searching by
filetype. So for example you could run (from within vim) :Ag --php "search
query". Unfortunately ag does not have irons for searching everything but a
specific filetype. You could open an issue with ag for that though.

**Comment by garand** [comment]
Great, thanks!
