### ISSUE TITLE
First Result Opens In Current Window

### ISSUE THREAD

**Issue by leesio** [rking/ag.vim#147]
Hey Guys,
Had a scan of the existing issues and couldn't see this listed, apologies if it's already been mentioned/is expected behaviour.

When I run a search with `:Ag something` the first result is automatically opened in the current window. Is this the expected behaviour? I seem to remember this not being the case previously. 🤔

EDIT: Just noticed the repo has been deprecated 🙁

**Comment by phsantiago** [comment]
Same to me.

**Comment by leesio** [comment]
@phsantiago I migrated over to https://github.com/mileszs/ack.vim [using ag](https://github.com/mileszs/ack.vim#can-i-use-ag-the-silver-searcher-with-this). It seems to work perfectly and the readme explains how to [avoid the problem](https://github.com/mileszs/ack.vim#i-dont-want-to-jump-to-the-first-result-automatically) I describe in this issue.

Since this repo is deprecated and I consider using `ack.vim` a perfectly acceptable solution, I'm going to close this issue.
