### ISSUE TITLE
Search highlighted word

### ISSUE THREAD

**Issue by abacha** [rking/ag.vim#153]
Is it possible to bind a shortcut (ie _leader_ G) to do :Ag <word>?

**Comment by benoittgt** [comment]
I have this shortcut in my vimrc
```viml
nnoremap <leader>k :exe 'Ag!' expand('<cword>')<cr>
```

It searches the word under cursor. For highlighted word [this is less easy](http://stackoverflow.com/questions/1533565/how-to-get-visually-selected-text-in-vimscript)

**Comment by zack** [comment]
This works for me:

`vnoremap <leader>G "hy:Ag "<C-r>h"<CR>`

I'm not sure if I'm missing something? The comment thread above implies a significant amount of difficulty that I'm just not seeing.
