### ISSUE TITLE
unrecognized option '--vimgrep'

### ISSUE THREAD

**Issue by tomleo** [rking/ag.vim#82]
I installed ag.vim via vundle

When I search for something like `:Ag car_names .` I'm prompted with an error and usage information

```
ag: unrecognized option '--vimgrep'
```

**Comment by mbarrin** [comment]
I am getting the same issue.

**Comment by losingkeys** [comment]
Sorry about that. I didn't realize how new the `--vimgrep` option was. For the meantime you can set
```vim
let g:ag_prg="ag --column"
```
In your `~/.vimrc`. Upgrading to a newer version of ag will also fix this.

**Comment by tomleo** [comment]
@losingkeys That did the trick thanks!

**Comment by mbarrin** [comment]
I just upgraded my ag. Thanks for the response :)
