### ISSUE TITLE
Search results get "lost" if a file doesn't end with a newline

### ISSUE THREAD

**Issue by Ipsquiggle** [rking/ag.vim#93]
Some text editors (for example, ones used by most of my team at work here) don't always append a newline at the end of a file. This causes weird Ag output, which then causes weird behaviour from Ag.vim in the scenario where the last result from a file is on the last line and the file doesn't end with a newline.

Take this example:

    a.txt:
    foo
    
    b.txt:
    foo\n
    foo\n
    
    c.txt:
    foo\n

Note that a.txt was made by a crummy text editor and has no trailing newline.

If we run this through Ag at the command line, we get this:

    a.txt
    1:foo
    b.txt
    1:foo
    2:foo

    c.txt
    1:foo

You can see that there are all 4 results, but we are missing blank between the output from a.txt and the output from b.txt. This is generally what I expect from a unixy program (dumb as it may be) so I think Ag is behaving "correctly" in this case. (If you disagree, let me know and I'll bring this up on Ag tracker instead.)

If we do a search in Vim, we get this quickfix:

    a.txt|1 col 1| foo
    b.txt|2 col 1| foo
    c.txt|1 col 1| foo

You can see that the first result from b.txt has been excluded from the quickfix list. This happens very consistently for me in this scenario. This is particularly maddening because if a file only has one result, it doesn't show at all, and if multiple files meet this criteria (a result on the last line with no newline) then whole chunks of results can vanish.

**Comment by losingkeys** [comment]
[Cannot reproduce](https://asciinema.org/a/dhw6qhnl60vzo4b31288he656). You can see that `a.txt` in that demo doesn't have a trailing newline because zsh shows its EOF as `%`.

I'm running ag 0.30.0 and vim 7.4.778. Which versions do you have?

**Comment by Ipsquiggle** [comment]
Hey, sorry I never responded. This issue no longer happens to me, I'm supposing now it was a bug in my version of Ag that had since been fixed. (In my test, Ag now always puts a newline between results, even if the line doesn't end in a newline.) Thanks for your effort!
