### ISSUE TITLE
How to search from the root of project?

### ISSUE THREAD

**Issue by aerohit** [rking/ag.vim#94]
Hello,

When I search for a text using ":Ag <pattern>", it searches inside files contained inside the directory of the current buffer. Is it possible to tell Ag, to search from the root of the project instead. I use git for version control, so maybe using that to determine the root of the project in some way.

Thanks.

**Comment by losingkeys** [comment]
We could add a `:AgGit` and `:AgHg` command to use the directories pointed to by [`git rev-parse --show-toplevel`](https://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command/957978#957978) and [`hg root`](https://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command).

Maybe `:AgRoot` or `:AgProject` would detect the type of project and search the `$PWD` if none was detected?

Bonus points for old/less popular VCS' (svn, bzr, cvs, etc, etc).

**Comment by Numkil** [comment]
It would be cool if ag.vim uses the same way of determining where you want it to start looking, as is used in ctrlp.

let g:ctrlp_working_path_mode = 'ra'

'c' - the directory of the current file.
'r' - the nearest ancestor that contains one of these directories or files: .git .hg .svn .bzr _darcs
'a' - like c, but only if the current working directory outside of CtrlP is not a direct ancestor of the directory of the current file.

I'm looking in to how possible it might be to rewrite some of ctrlp code  for ag.vim but I've never worked on any vim plugins before so I don't really know what I'm doing yet.

**Comment by Numkil** [comment]
I wrote this little thing, which seems to work for me. Numkil/ag.vim@466ef221b6928e92c60948dc5ff5936559c26afa

Can you let me know what you think of it and if you would consider merging it into your code? I'll of course update the documentation and rewrite any parts you do not agree with. 

@losingkeys it should support the older filetypes you specified.

**Comment by Numkil** [comment]
This has been merged already in #99, safe to close this.
