### ISSUE TITLE
how to search only within files of certain extension in a given dir

### ISSUE THREAD

**Issue by assaflavie** [rking/ag.vim#97]
Is it possible to search for a string within all files with a given extension (e.g. "*.py") in a specific directory?

:Ag some-string myrepo/

Let's me search only in a given directory, but how do I also apply a file-extension filter?

**Comment by losingkeys** [comment]
Sure. You can always pass options directly to `ag` from this wrapper. If you have a recent version of ag, `:Ag --python searchstring directory/` should work. Have a look at [the manual](https://www.mankier.com/1/ag#File_Types) for more info.
